langage: ruby
rvm:
    - 2.2.4
cache: bundler
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - bundle exec rake db:migrate
script:
    - bundle exec rspec spec
